// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/28 08:54:42
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/10779/NuxtProject/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/10779/NuxtProject/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/10779/NuxtProject/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/10779/NuxtProject/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/10779/NuxtProject/plugins/**/*.{js,ts,mjs}","C:/Users/10779/NuxtProject/composables/**/*.{js,ts,mjs}","C:/Users/10779/NuxtProject/utils/**/*.{js,ts,mjs}","C:/Users/10779/NuxtProject/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/10779/NuxtProject/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/10779/NuxtProject/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/10779/NuxtProject/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;